dovecot_config_version = 2.4.4
dovecot_storage_version = 2.4.4

listen = 127.0.0.1
protocols = imap

mail_driver = maildir
mail_gid = vmail
mail_home = /vmail/%{user | domain}/%{user | username}
mail_inbox_path = %{home}/Maildir
mail_path = %{home}/Maildir
mail_privileged_group = mail
mail_uid = vmail

ssl = required
ssl_server {
  cert_file = /etc/ssl/certs/mailbridge-cert.pem
  key_file = /etc/ssl/private/mailbridge-key.pem
}

namespace inbox {
  inbox = yes
  mailbox Drafts {
    special_use = "\Drafts"
  }
  mailbox Junk {
    special_use = "\Junk"
  }
  mailbox Trash {
    special_use = "\Trash"
  }
  mailbox Sent {
    special_use = "\Sent"
  }
  mailbox "Sent Messages" {
    special_use = "\Sent"
  }
}

service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = postfix
    mode = 0660
    user = postfix
  }
}

passdb passwd-file {
  auth_username_format = %{user}
  default_password_scheme = SHA512-CRYPT
  passwd_file_path = /etc/dovecot/users
}

userdb passwd-file {
  auth_username_format = %{user}
  passwd_file_path = /etc/dovecot/users
}
